### ISSUE TITLE
Erro ortográfico

### ISSUE THREAD

**Issue by pesdesigner** [codepes/github#1]
Erro de escrita: add paragafo
correção: parágrafo

**Comment by codepes** [comment]
Ok, irei fazer a correção, Obrigado!

**Comment by codepes** [comment]
Muito obrigado pela sua colaboração!

codePes - Paulo Eduardo de Souza
Conheça meus projetos:
* Site: [Gráfico e Web](https://graficoeweb.com.br/)
* Linkedin: [Linkedin](https://www.linkedin.com/in/paulo-eduardo-47646596/)
